module.exports = {
    'begin-end-time': '起止时间',
    'unit.day': '天',
    'study.member.count': '人已学习',
    'the.latest': '最新',
    'the.hottest': '最热',
    'the.high.praise': '好评',
    'search.subject.placeholder': '请输入你需要寻找的专题',
    'subject.description': '描述',
    'subject.study.day': '目标天数',
    'subject.rest.day': '剩余天数',
    'btn.prefix': '进入',
    'check.the.record': '查看记录',
    'study.total.time': '学习累计时长',
    'left.page': '向左翻',
    'right.page': '向右翻',
    'reset.page': '换一组',
    'study.task.attachment': '作业附件',
    'study.user.attachment': '用户提交的：',
    'study.my.submit': '我提交的：'
};
